import { FAQ } from "./constants";
import type { Locale } from "./i18n";

export interface FaqItem {
  question: string;
  answer: string;
}

// Translations aligned by index to FAQ in constants.ts (13 items).
// English is the source (from constants); any missing item falls back to it.
const FAQ_I18N: Partial<Record<Locale, FaqItem[]>> = {
  ru: [
    { question: "Нужен ли Lumi доступ к моему банковскому счёту?", answer: "Нет. Lumi никогда не запрашивает банковские данные, номера карт или доступ к финансовым учреждениям. Все данные хранятся локально на устройстве. Транзакции Apple Pay импортируются через iOS Shortcuts — разовая настройка без доступа третьих лиц." },
    { question: "Как работает запись через Back Tap?", answer: "Back Tap — встроенный жест доступности iOS: двойное касание задней панели iPhone запускает нужное действие. В Lumi он открывает приложение сразу в режиме записи расхода. Без разблокировки, поиска приложения и лишних нажатий — расход записывается менее чем за 3 секунды." },
    { question: "Как работает авто-импорт Apple Pay?", answer: "Настройте разовый iOS-ярлык, который срабатывает при оплате Apple Pay. Каждый бесконтактный платёж автоматически создаёт запись расхода в Lumi с суммой, названием продавца и временем. После настройки ручной ввод не нужен." },
    { question: "Можно ли записывать расходы голосом?", answer: "Да. Нажмите на иконку микрофона и скажите, например, «кофе 5 евро» или «метро 2 евро» — ИИ Lumi распознаёт сумму, продавца и категорию прямо из речи и мгновенно записывает расход. Без набора текста и меню, поддерживает несколько языков." },
    { question: "Насколько точен ИИ-прогноз расходов?", answer: "Lumi рассчитывает средний дневной темп трат за последние 3 месяца (исключая статистические выбросы вроде разовых крупных покупок) и проецирует его на конец месяца. Если введены данные о доходе, показывается и прогноз баланса. Показатель уверенности всегда виден, так что вы знаете надёжность прогноза." },
    { question: "Есть ли Lumi на Android?", answer: "Нет. Lumi — приложение для iPhone, версии для Android не будет. Back Tap, автоимпорт Apple Pay и Быстрые команды — функции iOS, и Lumi построен вокруг них." },
    { question: "Какие валюты поддерживает Lumi?", answer: "Бесплатный план включает 2 валюты с конвертацией в реальном времени. Premium — 150+ валют с автоматическим обновлением курсов. Удобно для путешествий, жизни за рубежом и дохода в нескольких валютах." },
    { question: "Мои финансовые данные приватны и защищены?", answer: "Все данные хранятся исключительно на вашем устройстве — у Lumi нет серверов, хранящих ваши транзакции. Аккаунт для использования не нужен. Данные не продаются и не передаются третьим лицам. Всё можно экспортировать или удалить в любой момент." },
    { question: "Как работает сканер чеков?", answer: "Наведите камеру iPhone на любой бумажный или электронный чек. ИИ-зрение Lumi считывает сумму, дату, название продавца и назначает категорию — даже для чеков на иностранных языках. Сканирование занимает 2–3 секунды." },
    { question: "Как работают бюджеты по категориям в Lumi?", answer: "Задайте месячный лимит для любой категории — продукты, кафе, транспорт, подписки и т.д. Lumi отслеживает траты относительно лимита в реальном времени с живым индикатором и предупреждает по мере приближения, а не после перерасхода. В бесплатном плане 2 бюджета, в Premium — без ограничений." },
    { question: "Как работают цели накоплений в Lumi?", answer: "Создайте цель с целевой суммой и, при желании, сроком — поездка, подушка безопасности, крупная покупка. Записывайте пополнения, а Lumi отслеживает прогресс с процентной шкалой, вехами и остатком до цели. Можно вести несколько целей одновременно." },
    { question: "Lumi бесплатен?", answer: "Да. Бесплатный план включает 10 ИИ-сканирований чеков в месяц, 2 бюджета, запись через Back Tap, авто-импорт Apple Pay, голосовой ввод и базовую аналитику. Lumi Premium ($4.99/мес или $39.99/год) открывает безлимитные сканирования, безлимитные бюджеты, ИИ-прогноз, продвинутую аналитику и полную мультивалютность." },
    { question: "Чем Lumi отличается от YNAB, Copilot или Monarch?", answer: "Три вещи, которых нет одновременно ни у одного конкурента: (1) мгновенная запись через Back Tap — без открытия приложения; (2) авто-импорт Apple Pay — запись без усилий; (3) локальная приватность — без входа в банк, без облака, данные не покидают телефон. YNAB, Monarch и Copilot требуют доступа к банковскому счёту и хранят данные в облаке." },
  ],
  uk: [
    { question: "Чи потрібен Lumi доступ до мого банківського рахунку?", answer: "Ні. Lumi ніколи не запитує банківські дані, номери карток чи доступ до фінансових установ. Усі дані зберігаються локально на пристрої. Транзакції Apple Pay імпортуються через iOS Shortcuts — разове налаштування без доступу третіх осіб." },
    { question: "Як працює запис через Back Tap?", answer: "Back Tap — вбудований жест доступності iOS: подвійний дотик до задньої панелі iPhone запускає потрібну дію. У Lumi він відкриває застосунок одразу в режимі запису витрати. Без розблокування, пошуку застосунку й зайвих натискань — витрата записується менш ніж за 3 секунди." },
    { question: "Як працює авто-імпорт Apple Pay?", answer: "Налаштуйте разовий iOS-ярлик, що спрацьовує під час оплати Apple Pay. Кожен безконтактний платіж автоматично створює запис витрати в Lumi із сумою, назвою продавця та часом. Після налаштування ручне введення не потрібне." },
    { question: "Чи можна записувати витрати голосом?", answer: "Так. Натисніть іконку мікрофона і скажіть, наприклад, «кава 5 євро» або «метро 2 євро» — ШІ Lumi розпізнає суму, продавця й категорію просто з мовлення та миттєво записує витрату. Без набору тексту й меню, підтримує кілька мов." },
    { question: "Наскільки точний ШІ-прогноз витрат?", answer: "Lumi обчислює середній денний темп витрат за останні 3 місяці (виключаючи статистичні викиди на кшталт разових великих покупок) і проєктує його на кінець місяця. Якщо введено дані про дохід, показується й прогноз балансу. Показник впевненості завжди видно, тож ви знаєте надійність прогнозу." },
    { question: "Чи є Lumi на Android?", answer: "Ні. Lumi — застосунок для iPhone, версії для Android не буде. Back Tap, автоімпорт Apple Pay і Швидкі команди — функції iOS, і Lumi побудований навколо них." },
    { question: "Які валюти підтримує Lumi?", answer: "Безкоштовний план включає 2 валюти з конвертацією в реальному часі. Premium — 150+ валют з автоматичним оновленням курсів. Зручно для подорожей, життя за кордоном і доходу в кількох валютах." },
    { question: "Чи приватні та захищені мої фінансові дані?", answer: "Усі дані зберігаються виключно на вашому пристрої — у Lumi немає серверів, що зберігають ваші транзакції. Обліковий запис для користування не потрібен. Дані не продаються й не передаються третім особам. Усе можна експортувати або видалити будь-коли." },
    { question: "Як працює сканер чеків?", answer: "Наведіть камеру iPhone на будь-який паперовий чи електронний чек. ШІ-зір Lumi зчитує суму, дату, назву продавця та призначає категорію — навіть для чеків іноземними мовами. Сканування триває 2–3 секунди." },
    { question: "Як працюють бюджети за категоріями в Lumi?", answer: "Задайте місячний ліміт для будь-якої категорії — продукти, кафе, транспорт, підписки тощо. Lumi відстежує витрати відносно ліміту в реальному часі з живим індикатором і попереджає в міру наближення, а не після перевитрат. У безкоштовному плані 2 бюджети, у Premium — без обмежень." },
    { question: "Як працюють цілі накопичень у Lumi?", answer: "Створіть ціль із цільовою сумою та, за бажанням, строком — поїздка, фінансова подушка, велика покупка. Записуйте поповнення, а Lumi відстежує прогрес із відсотковою шкалою, віхами й залишком до цілі. Можна вести кілька цілей одночасно." },
    { question: "Чи безкоштовний Lumi?", answer: "Так. Безкоштовний план включає 10 ШІ-сканувань чеків на місяць, 2 бюджети, запис через Back Tap, авто-імпорт Apple Pay, голосове введення й базову аналітику. Lumi Premium ($4.99/міс або $39.99/рік) відкриває безлімітні сканування, безлімітні бюджети, ШІ-прогноз, розширену аналітику й повну мультивалютність." },
    { question: "Чим Lumi відрізняється від YNAB, Copilot чи Monarch?", answer: "Три речі, яких немає одночасно в жодного конкурента: (1) миттєвий запис через Back Tap — без відкриття застосунку; (2) авто-імпорт Apple Pay — запис без зусиль; (3) локальна приватність — без входу в банк, без хмари, дані не залишають телефон. YNAB, Monarch і Copilot вимагають доступу до банківського рахунку й зберігають дані у хмарі." },
  ],
  de: [
    { question: "Benötigt Lumi Zugriff auf mein Bankkonto?", answer: "Nein. Lumi fragt niemals nach Bankdaten, Kartennummern oder Zugang zu Finanzinstituten. Alle Daten werden lokal auf deinem Gerät gespeichert. Apple-Pay-Transaktionen werden über iOS-Kurzbefehle importiert — eine einmalige Einrichtung ohne Zugriff Dritter." },
    { question: "Wie funktioniert das Erfassen per Back Tap?", answer: "Back Tap ist eine integrierte iOS-Bedienungshilfe: Doppeltippen auf die Rückseite des iPhones löst eine Aktion aus. In Lumi öffnet es die App direkt im Erfassungsmodus. Kein Entsperren, kein Suchen der App, keine Extra-Taps — eine Ausgabe ist in unter 3 Sekunden erfasst." },
    { question: "Wie funktioniert der Apple-Pay-Auto-Import?", answer: "Richte einen einmaligen iOS-Kurzbefehl ein, der bei Apple-Pay-Zahlungen auslöst. Jede kontaktlose Zahlung erstellt automatisch einen Ausgabeneintrag in Lumi mit Betrag, Händlername und Zeitstempel. Nach der Einrichtung ist keine manuelle Eingabe nötig." },
    { question: "Kann ich Ausgaben per Sprache erfassen?", answer: "Ja. Tippe auf das Mikrofon-Symbol und sage etwa «Kaffee 5 Euro» oder «Metro 2 Euro» — die KI von Lumi erkennt Betrag, Händler und Kategorie direkt aus der Sprache und erfasst die Ausgabe sofort. Ohne Tippen, ohne Menüs, in mehreren Sprachen." },
    { question: "Wie genau ist die KI-Ausgabenprognose?", answer: "Lumi berechnet deine durchschnittliche tägliche Ausgabenrate der letzten 3 Monate (ohne statistische Ausreißer wie einmalige Großkäufe) und projiziert sie aufs Monatsende. Bei erfassten Einnahmen wird auch dein prognostizierter Saldo angezeigt. Konfidenzwerte zeigen stets, wie verlässlich die Prognose ist." },
    { question: "Gibt es Lumi für Android?", answer: "Nein. Lumi ist eine iPhone-App, eine Android-Version ist nicht geplant. Back Tap, der automatische Apple-Pay-Import und Kurzbefehle sind iOS-Funktionen, und Lumi ist um sie herum gebaut." },
    { question: "Welche Währungen unterstützt Lumi?", answer: "Der kostenlose Plan enthält 2 Währungen mit Echtzeit-Umrechnung. Premium bietet über 150 Währungen mit automatischen Wechselkurs-Updates. Ideal für Reisen, Leben im Ausland oder Einnahmen in mehreren Währungen." },
    { question: "Sind meine Finanzdaten privat und sicher?", answer: "Alle Daten werden ausschließlich auf deinem Gerät gespeichert — Lumi hat keine Server, die deine Transaktionen speichern. Für die Nutzung ist kein Konto nötig. Es werden keine Daten verkauft oder an Dritte weitergegeben. Du kannst jederzeit alles exportieren oder löschen." },
    { question: "Wie funktioniert der Belegscanner?", answer: "Richte die iPhone-Kamera auf einen beliebigen Papier- oder Digitalbeleg. Die KI-Vision von Lumi liest Betrag, Datum und Händlername und weist eine Kategorie zu — auch bei fremdsprachigen Belegen. Der Scan dauert 2–3 Sekunden." },
    { question: "Wie funktionieren Kategorie-Budgets in Lumi?", answer: "Lege ein Monatslimit für jede Kategorie fest — Lebensmittel, Essen, Transport, Abos und mehr. Lumi verfolgt deine Ausgaben in Echtzeit mit einem Fortschrittsbalken und warnt dich, wenn du dich dem Limit näherst, statt erst nach dem Überschreiten. Kostenlos: 2 Budgets, Premium: unbegrenzt." },
    { question: "Wie funktionieren Sparziele in Lumi?", answer: "Erstelle ein Sparziel mit Zielbetrag und optional einer Frist — eine Reise, ein Notgroschen, eine größere Anschaffung. Erfasse Einzahlungen, und Lumi verfolgt den Fortschritt mit Prozentbalken, Meilensteinen und dem verbleibenden Betrag. Mehrere Ziele gleichzeitig möglich." },
    { question: "Ist Lumi kostenlos?", answer: "Ja. Der kostenlose Plan umfasst 10 KI-Belegscans pro Monat, 2 Budgets, Back-Tap-Erfassung, Apple-Pay-Auto-Import, Spracheingabe und Basis-Analysen. Lumi Premium (4,99 $/Monat oder 39,99 $/Jahr) schaltet unbegrenzte Scans, unbegrenzte Budgets, KI-Prognose, erweiterte Analysen und volle Mehrwährungsunterstützung frei." },
    { question: "Was unterscheidet Lumi von YNAB, Copilot oder Monarch?", answer: "Drei Dinge, die kein Wettbewerber gleichzeitig bietet: (1) Sofort-Erfassung per Back Tap — ohne die App zu öffnen; (2) Apple-Pay-Auto-Import — müheloses automatisches Erfassen; (3) lokale Privatsphäre — kein Bank-Login, keine Cloud, deine Daten verlassen nie dein Telefon. YNAB, Monarch und Copilot erfordern Bankkonto-Zugang und speichern Daten in der Cloud." },
  ],
  es: [
    { question: "¿Lumi necesita acceso a mi cuenta bancaria?", answer: "No. Lumi nunca pide credenciales bancarias, números de tarjeta ni acceso a entidades financieras. Todos los datos se guardan localmente en tu dispositivo. Las transacciones de Apple Pay se importan mediante Atajos de iOS: una configuración única sin acceso de terceros." },
    { question: "¿Cómo funciona el registro con Back Tap?", answer: "Back Tap es un gesto de accesibilidad nativo de iOS: toca dos veces la parte trasera del iPhone para activar una acción. En Lumi abre la app directamente en modo de registro. Sin desbloquear, sin buscar la app, sin toques extra: registras un gasto en menos de 3 segundos." },
    { question: "¿Cómo funciona la importación automática de Apple Pay?", answer: "Configura un Atajo de iOS único que se activa al usar Apple Pay. Cada pago sin contacto crea automáticamente un gasto en Lumi con el importe, el comercio y la hora correctos. No hace falta introducir nada tras la configuración." },
    { question: "¿Puedo registrar gastos con la voz?", answer: "Sí. Toca el icono del micrófono y di algo como «café 5 euros» o «metro 2 euros»: la IA de Lumi extrae el importe, el comercio y la categoría directamente del habla y registra el gasto al instante. Sin escribir, sin menús, en varios idiomas." },
    { question: "¿Qué precisión tiene la previsión de gastos con IA?", answer: "Lumi calcula tu gasto medio diario de los últimos 3 meses (excluyendo valores atípicos como compras grandes puntuales) y lo proyecta a fin de mes. Si has introducido ingresos, también muestra tu saldo previsto. Los niveles de confianza indican siempre lo fiable que es la previsión." },
    { question: "¿Está Lumi disponible en Android?", answer: "No. Lumi es una app para iPhone y no habrá versión para Android. Back Tap, la importación automática de Apple Pay y Atajos son funciones de iOS, y Lumi está construida en torno a ellas." },
    { question: "¿Qué monedas admite Lumi?", answer: "El plan gratuito incluye 2 monedas con conversión en tiempo real. Premium incluye más de 150 monedas con actualización automática de tipos de cambio. Útil para viajes, vida en el extranjero o ingresos en varias monedas." },
    { question: "¿Mis datos financieros son privados y seguros?", answer: "Todos tus datos se guardan exclusivamente en tu dispositivo: Lumi no tiene servidores que almacenen tus transacciones. No se requiere cuenta para usar la app. No se venden ni comparten datos con terceros. Puedes exportar o borrar todo en cualquier momento." },
    { question: "¿Cómo funciona el escáner de recibos?", answer: "Apunta la cámara del iPhone a cualquier recibo en papel o digital. La visión con IA de Lumi lee el importe, la fecha y el comercio y asigna una categoría, incluso en recibos en otros idiomas. El escaneo tarda 2–3 segundos." },
    { question: "¿Cómo funcionan los presupuestos por categoría en Lumi?", answer: "Fija un límite mensual para cualquier categoría: supermercado, comidas, transporte, suscripciones, etc. Lumi sigue tu gasto frente al límite en tiempo real con una barra de progreso y te avisa al acercarte, en lugar de solo después de pasarte. El plan gratuito incluye 2 presupuestos; Premium, ilimitados." },
    { question: "¿Cómo funcionan las metas de ahorro en Lumi?", answer: "Crea una meta con un importe objetivo y, opcionalmente, una fecha límite: un viaje, un fondo de emergencia, una compra grande. Registra aportes y Lumi sigue tu progreso con una barra de porcentaje, hitos y el total que falta por ahorrar. Puedes tener varias metas a la vez." },
    { question: "¿Lumi es gratis?", answer: "Sí. El plan gratuito incluye 10 escaneos de recibos con IA al mes, 2 presupuestos, registro con Back Tap, importación automática de Apple Pay, entrada por voz y análisis básicos. Lumi Premium (4,99 $/mes o 39,99 $/año) desbloquea escaneos ilimitados, presupuestos ilimitados, previsión con IA, análisis avanzados y multidivisa completa." },
    { question: "¿En qué se diferencia Lumi de YNAB, Copilot o Monarch?", answer: "Tres cosas que ningún competidor ofrece a la vez: (1) registro instantáneo con Back Tap, sin abrir la app; (2) importación automática de Apple Pay, sin esfuerzo; (3) privacidad local: sin acceso bancario, sin nube, tus datos nunca salen del teléfono. YNAB, Monarch y Copilot exigen acceso a la cuenta bancaria y guardan los datos en la nube." },
  ],
  it: [
    { question: "Lumi ha bisogno di accedere al mio conto bancario?", answer: "No. Lumi non chiede mai credenziali bancarie, numeri di carta o accesso a istituti finanziari. Tutti i dati sono salvati localmente sul dispositivo. Le transazioni Apple Pay vengono importate tramite i Comandi rapidi di iOS: una configurazione una tantum senza accesso di terzi." },
    { question: "Come funziona la registrazione con Back Tap?", answer: "Back Tap è un gesto di accessibilità nativo di iOS: tocca due volte il retro dell'iPhone per attivare un'azione. In Lumi apre l'app direttamente in modalità registrazione. Senza sbloccare, senza cercare l'app, senza tocchi extra: registri una spesa in meno di 3 secondi." },
    { question: "Come funziona l'importazione automatica di Apple Pay?", answer: "Configura un Comando rapido di iOS che si attiva quando usi Apple Pay. Ogni pagamento contactless crea automaticamente una spesa in Lumi con importo, esercente e orario corretti. Dopo la configurazione non serve alcun inserimento manuale." },
    { question: "Posso registrare le spese con la voce?", answer: "Sì. Tocca l'icona del microfono e di' qualcosa come «caffè 5 euro» o «metro 2 euro»: l'IA di Lumi ricava importo, esercente e categoria direttamente dal parlato e registra la spesa all'istante. Senza digitare, senza menu, in più lingue." },
    { question: "Quanto è precisa la previsione di spesa con IA?", answer: "Lumi calcola la spesa media giornaliera degli ultimi 3 mesi (escludendo valori anomali come acquisti grandi occasionali) e la proietta a fine mese. Se hai inserito le entrate, mostra anche il saldo previsto. I punteggi di affidabilità indicano sempre quanto è attendibile la previsione." },
    { question: "Lumi è disponibile su Android?", answer: "No. Lumi è un'app per iPhone e non è prevista una versione Android. Back Tap, l'importazione automatica di Apple Pay e i Comandi rapidi sono funzioni di iOS, e Lumi è costruita attorno a queste." },
    { question: "Quali valute supporta Lumi?", answer: "Il piano gratuito include 2 valute con conversione in tempo reale. Premium include oltre 150 valute con aggiornamento automatico dei tassi. Utile per viaggi, vita all'estero o entrate in più valute." },
    { question: "I miei dati finanziari sono privati e sicuri?", answer: "Tutti i dati sono salvati esclusivamente sul tuo dispositivo: Lumi non ha server che memorizzano le tue transazioni. Non serve un account per usare l'app. Nessun dato viene venduto o condiviso con terzi. Puoi esportare o eliminare tutto in qualsiasi momento." },
    { question: "Come funziona lo scanner degli scontrini?", answer: "Inquadra con la fotocamera dell'iPhone qualsiasi scontrino cartaceo o digitale. L'IA Vision di Lumi legge importo, data ed esercente e assegna una categoria, anche per scontrini in lingue straniere. La scansione richiede 2–3 secondi." },
    { question: "Come funzionano i budget per categoria in Lumi?", answer: "Imposta un limite mensile per qualsiasi categoria: spesa, ristoranti, trasporti, abbonamenti e altro. Lumi monitora la spesa rispetto al limite in tempo reale con una barra di avanzamento e ti avvisa mentre ti avvicini, non solo dopo lo sforamento. Il piano gratuito include 2 budget; Premium è illimitato." },
    { question: "Come funzionano gli obiettivi di risparmio in Lumi?", answer: "Crea un obiettivo con un importo target e, facoltativamente, una scadenza: un viaggio, un fondo di emergenza, un acquisto importante. Registra i versamenti e Lumi monitora i progressi con barra percentuale, traguardi e quanto resta da risparmiare. Puoi gestire più obiettivi insieme." },
    { question: "Lumi è gratuito?", answer: "Sì. Il piano gratuito include 10 scansioni di scontrini con IA al mese, 2 budget, registrazione con Back Tap, importazione automatica di Apple Pay, input vocale e analisi di base. Lumi Premium (4,99 $/mese o 39,99 $/anno) sblocca scansioni illimitate, budget illimitati, previsione IA, analisi avanzate e multivaluta completa." },
    { question: "Cosa distingue Lumi da YNAB, Copilot o Monarch?", answer: "Tre cose che nessun concorrente offre insieme: (1) registrazione istantanea con Back Tap, senza aprire l'app; (2) importazione automatica di Apple Pay, senza sforzo; (3) privacy locale: nessun accesso bancario, nessun cloud, i tuoi dati non lasciano mai il telefono. YNAB, Monarch e Copilot richiedono l'accesso al conto e archiviano i dati nel cloud." },
  ],
  ro: [
    { question: "Are Lumi nevoie de acces la contul meu bancar?", answer: "Nu. Lumi nu solicită niciodată date bancare, numere de card sau acces la instituții financiare. Toate datele sunt stocate local pe dispozitiv. Tranzacțiile Apple Pay se importă prin Scurtături iOS — o configurare unică, fără acces terț." },
    { question: "Cum funcționează înregistrarea prin Back Tap?", answer: "Back Tap este un gest de accesibilitate nativ iOS: atinge de două ori spatele iPhone-ului pentru a declanșa o acțiune. În Lumi deschide aplicația direct în modul de înregistrare. Fără deblocare, fără căutarea aplicației, fără atingeri în plus — înregistrezi o cheltuială în mai puțin de 3 secunde." },
    { question: "Cum funcționează importul automat Apple Pay?", answer: "Configurează o Scurtătură iOS unică ce se declanșează la plata cu Apple Pay. Fiecare plată contactless creează automat o cheltuială în Lumi cu suma, comerciantul și ora corecte. După configurare nu mai e nevoie de introducere manuală." },
    { question: "Pot înregistra cheltuieli cu vocea?", answer: "Da. Atinge pictograma microfonului și spune, de exemplu, «cafea 5 euro» sau «metrou 2 euro» — IA Lumi extrage suma, comerciantul și categoria direct din vorbire și înregistrează cheltuiala instant. Fără tastare, fără meniuri, în mai multe limbi." },
    { question: "Cât de precisă este prognoza de cheltuieli cu IA?", answer: "Lumi calculează ritmul mediu zilnic de cheltuieli din ultimele 3 luni (excluzând valorile atipice, precum achizițiile mari ocazionale) și îl proiectează la finalul lunii. Dacă ai introdus venituri, afișează și soldul estimat. Scorurile de încredere arată mereu cât de fiabilă este prognoza." },
    { question: "Este Lumi disponibil pe Android?", answer: "Nu. Lumi este o aplicație pentru iPhone și nu va exista o versiune pentru Android. Back Tap, importul automat Apple Pay și Scurtăturile sunt funcții iOS, iar Lumi este construită în jurul lor." },
    { question: "Ce monede acceptă Lumi?", answer: "Planul gratuit include 2 monede cu conversie în timp real. Premium include peste 150 de monede cu actualizarea automată a cursurilor. Util pentru călătorii, viață în străinătate sau venituri în mai multe monede." },
    { question: "Datele mele financiare sunt private și sigure?", answer: "Toate datele sunt stocate exclusiv pe dispozitivul tău — Lumi nu are servere care să-ți stocheze tranzacțiile. Nu e nevoie de cont pentru a folosi aplicația. Datele nu sunt vândute și nu sunt partajate cu terți. Poți exporta sau șterge totul oricând." },
    { question: "Cum funcționează scanerul de bonuri?", answer: "Îndreaptă camera iPhone-ului spre orice bon pe hârtie sau digital. IA Vision de la Lumi citește suma, data și comerciantul și atribuie o categorie — chiar și pentru bonuri în limbi străine. Scanarea durează 2–3 secunde." },
    { question: "Cum funcționează bugetele pe categorii în Lumi?", answer: "Setează o limită lunară pentru orice categorie — alimente, mese, transport, abonamente etc. Lumi urmărește cheltuielile față de limită în timp real, cu o bară de progres, și te avertizează pe măsură ce te apropii, nu doar după depășire. Planul gratuit include 2 bugete; Premium este nelimitat." },
    { question: "Cum funcționează obiectivele de economisire în Lumi?", answer: "Creează un obiectiv cu o sumă țintă și, opțional, un termen — o călătorie, un fond de urgență, o achiziție mare. Înregistrează contribuțiile, iar Lumi urmărește progresul cu o bară procentuală, etape și cât mai rămâne de economisit. Poți gestiona mai multe obiective simultan." },
    { question: "Este Lumi gratuit?", answer: "Da. Planul gratuit include 10 scanări de bonuri cu IA pe lună, 2 bugete, înregistrare prin Back Tap, import automat Apple Pay, introducere vocală și analize de bază. Lumi Premium (4,99 $/lună sau 39,99 $/an) deblochează scanări nelimitate, bugete nelimitate, prognoză IA, analize avansate și suport complet multi-monedă." },
    { question: "Prin ce diferă Lumi de YNAB, Copilot sau Monarch?", answer: "Trei lucruri pe care niciun concurent nu le oferă simultan: (1) înregistrare instant prin Back Tap — fără a deschide aplicația; (2) import automat Apple Pay — fără efort; (3) confidențialitate locală — fără autentificare bancară, fără cloud, datele nu-ți părăsesc telefonul. YNAB, Monarch și Copilot necesită acces la contul bancar și stochează datele în cloud." },
  ],
};

export function getLocalizedFaq(locale: Locale): FaqItem[] {
  const base = FAQ.map((x) => ({ question: x.question, answer: x.answer }));
  if (locale === "en") return base;
  const tr = FAQ_I18N[locale];
  return base.map((item, i) => tr?.[i] ?? item);
}
